apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dara-zip-d4c9f
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/dara-zip-d4c9f.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dara-zip-d4c9f
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
